In [1]:
import warnings
warnings.simplefilter(action='ignore')
import numpy, pandas

In [2]:
train = pandas.read_csv('/kaggle/input/zelestra-phase-2-data/Dataset 1.csv')
train = train[train['ppc_p_tot'] != 0]
train.head()

,datetime,meteorolgicas_em_03_02_gii,meteorolgicas_em_08_01_gii,meteorolgicas_em_03_02_ghi,meteorolgicas_em_08_01_ghi,meteorolgicas_em_08_01_gii_rear,meteorolgicas_em_03_02_gii_rear,meteorolgicas_em_03_02_desviacin_incidente,meteorolgicas_em_08_01_desviacin_incidente,meteorolgicas_em_03_02_t_amb,...,seguidores_ct08_gcu081_t0808029_pos_ang,seguidores_ct08_gcu081_t0808029_workingmode,seguidores_ct03_gcu031_t0308035_pos_ang,seguidores_ct03_gcu031_t0308035_pos_obj,seguidores_ct03_gcu031_t0308035_workingmode,ppc_consig_p,ppc_p_tot,ppc_eact_export,ttr_potenciaproducible,ppc_eact_imp
32,2024-10-01 08:00:00,7.333333,8.000000,7.666667,5.500000,2.000000,2.400000,-7.821959,2.394106,15.163851,...,0.1,NaN,0.3,0.0,NaN,43.485001,0.187286,0.006,0.280974,0.032
33,2024-10-01 08:15:00,37.290323,38.870968,29.333333,27.833333,6.000000,9.583333,0.263388,-21.803244,15.318239,...,0.2,NaN,0.3,0.0,NaN,43.485001,1.487167,0.002,1.855950,0.348
34,2024-10-01 08:30:00,99.862745,100.943396,69.208333,67.920000,13.764706,15.176471,-0.741481,-1.327309,15.506113,...,0.2,NaN,0.2,0.0,NaN,43.485001,4.286884,0.000,4.714029,0.960
35,2024-10-01 08:45:00,182.830189,182.242424,110.960000,105.195122,22.000000,29.590909,0.167385,-3.363449,15.996723,...,0.1,NaN,0.3,0.0,NaN,43.485001,7.846769,0.000,8.724878,1.940
36,2024-10-01 09:00:00,283.886792,268.098039,160.100000,152.114286,18.500000,22.250000,-0.499285,-6.365527,16.399678,...,0.2,NaN,0.3,-0.3,NaN,43.485001,12.446891,0.000,13.372142,3.112

In [3]:
numpy.array(train.columns)

array(['datetime', 'meteorolgicas_em_03_02_gii',
       'meteorolgicas_em_08_01_gii', 'meteorolgicas_em_03_02_ghi',
       'meteorolgicas_em_08_01_ghi', 'meteorolgicas_em_08_01_gii_rear',
       'meteorolgicas_em_03_02_gii_rear',
       'meteorolgicas_em_03_02_desviacin_incidente',
       'meteorolgicas_em_08_01_desviacin_incidente',
       'meteorolgicas_em_03_02_t_amb', 'meteorolgicas_em_08_01_t_amb',
       'meteorolgicas_em_03_02_h_r', 'meteorolgicas_em_08_01_h_r',
       'meteorolgicas_em_03_02_t_dlogger',
       'meteorolgicas_em_08_01_t_dlogger', 'meteorolgicas_em_08_01_ws',
       'meteorolgicas_em_03_02_ws', 'meteorolgicas_em_08_01_wd',
       'meteorolgicas_em_03_02_wd', 'celulas_ctin08_cc_08_1_ir_cel_1',
       'celulas_ctin08_cc_08_2_ir_cel_1',
       'celulas_ctin03_cc_03_1_ir_cel_1',
       'celulas_ctin03_cc_03_2_ir_cel_1',
       'celulas_ctin08_cc_08_2_ir_cel_2',
       'celulas_ctin03_cc_03_2_ir_cel_2',
       'celulas_ctin03_cc_03_1_ir_cel_2',
       'celulas_ctin08_cc_08_1_ir_cel_2', 'celulas_ctin08_cc_08_2_t_amb',
       'celulas_ctin03_cc_03_1_t_amb', 'celulas_ctin08_cc_08_1_t_amb',
       'celulas_ctin03_cc_03_2_t_amb', 'celulas_ctin03_cc_03_1_t_mod',
       'celulas_ctin08_cc_08_2_t_mod', 'celulas_ctin03_cc_03_2_t_mod',
       'celulas_ctin08_cc_08_1_t_mod',
       'celulas_ctin03_cc_03_2_wind_speed',
       'celulas_ctin08_cc_08_1_wind_speed',
       'celulas_ctin08_cc_08_2_wind_speed',
       'celulas_ctin03_cc_03_1_wind_speed',
       'inversores_ctin03_strings_string8_pv_v',
       'inversores_ctin03_strings_string8_pv_i9',
       'inversores_ctin03_strings_string8_pv_i13',
       'inversores_ctin03_strings_string8_pv_i1',
       'inversores_ctin03_strings_string8_pv_i6',
       'inversores_ctin03_strings_string8_pv_i4',
       'inversores_ctin03_strings_string8_pv_i11',
       'inversores_ctin03_strings_string8_pv_i10',
       'inversores_ctin03_strings_string8_pv_i2',
       'inversores_ctin03_strings_string8_pv_i5',
       'inversores_ctin03_strings_string8_pv_i7',
       'inversores_ctin03_strings_string8_pv_i12',
       'inversores_ctin03_strings_string8_pv_i3',
       'inversores_ctin03_strings_string8_pv_i8',
       'inversores_ctin03_strings_string10_pv_i9',
       'inversores_ctin03_strings_string10_pv_i7',
       'inversores_ctin03_strings_string10_pv_i4',
       'inversores_ctin03_strings_string10_pv_i12',
       'inversores_ctin03_strings_string10_pv_i8',
       'inversores_ctin03_strings_string10_pv_i13',
       'inversores_ctin03_strings_string10_pv_i10',
       'inversores_ctin03_strings_string10_pv_i6',
       'inversores_ctin03_strings_string10_pv_i11',
       'inversores_ctin03_strings_string10_pv_i5',
       'inversores_ctin03_strings_string10_pv_i1',
       'inversores_ctin03_strings_string10_pv_i3',
       'inversores_ctin03_strings_string10_pv_i2',
       'inversores_ctin03_strings_string10_pv_v',
       'inversores_ctin08_strings_string9_pv_i12',
       'inversores_ctin08_strings_string9_pv_i13',
       'inversores_ctin08_strings_string9_pv_i1',
       'inversores_ctin08_strings_string9_pv_i7',
       'inversores_ctin08_strings_string9_pv_i8',
       'inversores_ctin08_strings_string9_pv_i6',
       'inversores_ctin08_strings_string9_pv_i10',
       'inversores_ctin08_strings_string9_pv_i9',
       'inversores_ctin08_strings_string9_pv_i11',
       'inversores_ctin08_strings_string9_pv_i4',
       'inversores_ctin08_strings_string9_pv_i5',
       'inversores_ctin08_strings_string9_pv_i2',
       'inversores_ctin08_strings_string9_pv_i3',
       'inversores_ctin08_strings_string9_pv_v',
       'inversores_ctin08_strings_string12_pv_i4',
       'inversores_ctin08_strings_string12_pv_i1',
       'inversores_ctin08_strings_string12_pv_i5',
       'inversores_ctin08_strings_string12_pv_i7',
       'inversores_ctin08_strings_string12_pv_i3',
       'inversores_ctin08_strings_string12_pv_i6',
       'inversores_ctin08_strings_string12_pv_i2',
       'inversores_ctin08_strings_string12_pv_i8',
       'inversores_ctin08_strings_string12_pv_i9',
       'inversores_ctin08_strings_string12_pv_i10',
       'inversores_ctin08_strings_string12_pv_v',
       'inversores_ctin08_inv_08_08_p', 'inversores_ctin03_inv_03_03_p',
       'inversores_ctin03_inv_03_03_p_dc',
       'inversores_ctin08_inv_08_08_p_dc',
       'inversores_ctin03_inv_03_03_eact_tot',
       'inversores_ctin08_inv_08_08_eact_tot',
       'seguidores_ct08_gcu081_t0808029_pos_obj',
       'seguidores_ct08_gcu081_t0808029_pos_ang',
       'seguidores_ct08_gcu081_t0808029_workingmode',
       'seguidores_ct03_gcu031_t0308035_pos_ang',
       'seguidores_ct03_gcu031_t0308035_pos_obj',
       'seguidores_ct03_gcu031_t0308035_workingmode', 'ppc_consig_p',
       'ppc_p_tot', 'ppc_eact_export', 'ttr_potenciaproducible',
       'ppc_eact_imp'], dtype=object)

In [4]:
#common
hr_03 = train[['meteorolgicas_em_03_02_h_r']]
hr_08 = train[['meteorolgicas_em_08_01_h_r']]

ws_03 = train[['meteorolgicas_em_03_02_ws']]
ws_08 = train[['meteorolgicas_em_08_01_ws']]

wd_03 = train[['meteorolgicas_em_03_02_wd']]
wd_08 = train[['meteorolgicas_em_08_01_wd']]

In [5]:
#cloud_cover and shading
ctin03 = train[['celulas_ctin03_cc_03_1_ir_cel_1', 
                'celulas_ctin03_cc_03_1_ir_cel_2', 
                'celulas_ctin03_cc_03_2_ir_cel_1', 
                'celulas_ctin03_cc_03_2_ir_cel_2']]

ctin08 = train[['celulas_ctin08_cc_08_1_ir_cel_1', 
                'celulas_ctin08_cc_08_1_ir_cel_2',
                'celulas_ctin08_cc_08_2_ir_cel_1', 
                'celulas_ctin08_cc_08_2_ir_cel_2']]

In [6]:
#temperature
em_03 = train[['meteorolgicas_em_03_02_t_dlogger']]
em_08 = train[['meteorolgicas_em_08_01_t_dlogger']]

In [7]:
numpy.array(em_03)[:30]

array([[15.29083252],
       [15.21994019],
       [15.43008423],
       [15.88471985],
       [16.82305908],
       [17.38952637],
       [18.37432861],
       [19.33334351],
       [20.22781372],
       [21.69831848],
       [22.79193115],
       [23.73657227],
       [24.80926514],
       [25.50123596],
       [26.48416138],
       [26.78962708],
       [27.03770447],
       [27.2925415 ],
       [27.67709351],
       [28.28775024],
       [28.78463745],
       [29.30197144],
       [29.83068848],
       [30.04544067],
       [30.36499023],
       [30.84387207],
       [31.37091064],
       [31.6730957 ],
       [32.05841064],
       [32.415802  ]])

In [8]:
Date_Time = numpy.array(train[['datetime', 
                               'celulas_ctin03_cc_03_1_ir_cel_1', 
                               'celulas_ctin08_cc_08_1_ir_cel_1', 
                               'celulas_ctin03_cc_03_1_ir_cel_2', 
                               'celulas_ctin08_cc_08_1_ir_cel_2',
                               'meteorolgicas_em_03_02_t_dlogger', 
                               'meteorolgicas_em_08_01_t_dlogger']])

T_error = (numpy.array(train[['ppc_p_tot']])-numpy.array(train[['ttr_potenciaproducible']])).reshape(-1)
neer_error = numpy.array([list(T)+[E] for E, T in zip(T_error, Date_Time) if E > -0.1 and E < 0.1])

pandas.DataFrame({'datetime' : numpy.array([i[0] for i in neer_error]),
                  'celulas_ctin03_cc_03_1_ir_cel_1' : numpy.array([float(i[1]) for i in neer_error]),
                  'celulas_ctin08_cc_08_1_ir_cel_1' : numpy.array([float(i[2]) for i in neer_error]),
                  'celulas_ctin03_cc_03_1_ir_cel_2' : numpy.array([float(i[3]) for i in neer_error]),
                  'celulas_ctin08_cc_08_1_ir_cel_2' : numpy.array([float(i[4]) for i in neer_error]),
                  'meteorolgicas_em_03_02_t_dlogger' : numpy.array([float(i[5]) for i in neer_error]),
                  'meteorolgicas_em_08_01_t_dlogger' : numpy.array([float(i[6]) for i in neer_error]),
                  'T_error' : numpy.array([float(i[7]) for i in neer_error])})

,datetime,celulas_ctin03_cc_03_1_ir_cel_1,celulas_ctin08_cc_08_1_ir_cel_1,celulas_ctin03_cc_03_1_ir_cel_2,celulas_ctin08_cc_08_1_ir_cel_2,meteorolgicas_em_03_02_t_dlogger,meteorolgicas_em_08_01_t_dlogger,T_error
0,2024-10-01 08:00:00,9.125000,9.000000,9.000000,9.500000,15.290833,14.298004,-0.093688
1,2024-10-01 17:45:00,208.812500,232.120000,209.357143,230.846154,30.299591,29.947876,-0.068642
2,2024-10-01 19:45:00,7.333333,6.428571,9.000000,7.000000,27.363495,27.621338,-0.071827
3,2024-10-02 09:45:00,230.200000,248.600000,230.642857,248.333333,25.096090,24.113739,-0.019958
4,2024-10-02 15:45:00,656.200000,638.958333,641.200000,627.366667,37.365189,36.910706,-0.016133
...,...,...,...,...,...,...,...,...
645,2025-03-29 06:45:00,3.000000,1.666667,1.666667,5.000000,13.676422,14.163223,-0.071596
646,2025-03-29 07:00:00,10.500000,10.000000,10.500000,10.100000,13.938416,14.262543,0.071230
647,2025-03-29 19:15:00,6.428571,4.375000,7.285714,6.625000,21.773682,22.034790,-0.091161
648,2025-03-30 20:15:00,6.000000,5.625000,7.555556,6.222222,18.025024,18.240097,-0.037230
649,2025-03-31 20:15:00,5.833333,6.250000,6.428571,5.333333,23.159241,23.422501,-0.078941

In [9]:
#average
average = {'celulas_ctin03_cc_03_1_ir_cel_1' : numpy.average(numpy.nan_to_num(numpy.array([float(i[1]) for i in neer_error]), nan=0)),
           'celulas_ctin03_cc_03_1_ir_cel_2' : numpy.average(numpy.nan_to_num(numpy.array([float(i[3]) for i in neer_error]), nan=0)),
           'celulas_ctin08_cc_08_1_ir_cel_1' : numpy.average(numpy.nan_to_num(numpy.array([float(i[2]) for i in neer_error]), nan=0)),
           'celulas_ctin08_cc_08_1_ir_cel_2' : numpy.average(numpy.nan_to_num(numpy.array([float(i[4]) for i in neer_error]), nan=0)),
           'meteorolgicas_em_03_02_t_dlogger' : numpy.average(numpy.nan_to_num(numpy.array([float(i[5]) for i in neer_error]), nan=0)),
           'meteorolgicas_em_08_01_t_dlogger' : numpy.average(numpy.nan_to_num(numpy.array([float(i[6]) for i in neer_error]), nan=0)),
           'T_error' : numpy.average(numpy.nan_to_num(numpy.array([float(i[7]) for i in neer_error]), nan=0))}

for i in average.keys():
    print(f'{i} : {average[i]}')

celulas_ctin03_cc_03_1_ir_cel_1 : 191.55154522614137
celulas_ctin03_cc_03_1_ir_cel_2 : 192.06983620225927
celulas_ctin08_cc_08_1_ir_cel_1 : 192.7571798425501
celulas_ctin08_cc_08_1_ir_cel_2 : 192.67478258907684
meteorolgicas_em_03_02_t_dlogger : 16.68845584967198
meteorolgicas_em_08_01_t_dlogger : 16.756842862642728
T_error : -0.013528640950499765