In [1]:
import warnings
warnings.simplefilter(action='ignore')

import os
import requests
import joblib

import numpy, pandas
import pandas as pd

import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
from catboost import CatBoostRegressor ,Pool
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from sklearn.linear_model import ElasticNetCV
from sklearn.linear_model import LassoCV
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import LassoLars
from sklearn.linear_model import Lasso
from sklearn.linear_model import BayesianRidge
from sklearn.linear_model import TweedieRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

from sklearn.neural_network import MLPRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.cross_decomposition import PLSRegression
from sklearn.cluster import KMeans
from sklearn.neighbors import NearestCentroid

from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import CategoricalNB

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor

from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.ensemble import StackingRegressor

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

from sklearn.pipeline import make_pipeline
from sklearn.model_selection import KFold, cross_val_score

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectFromModel

from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score

In [3]:
os.makedirs('data', exist_ok=True)
os.makedirs('model', exist_ok=True)

In [4]:
train = pandas.read_csv('/kaggle/input/zelestra-phase-2-data/Dataset 1.csv')

In [5]:
train = train[['meteorolgicas_em_08_01_gii', 'celulas_ctin08_cc_08_2_ir_cel_2', 'celulas_ctin08_cc_08_2_ir_cel_1', 
               'celulas_ctin08_cc_08_1_ir_cel_2', 'celulas_ctin08_cc_08_1_ir_cel_1', 'meteorolgicas_em_08_01_ghi', 
               'meteorolgicas_em_03_02_gii', 'celulas_ctin03_cc_03_1_ir_cel_1', 'celulas_ctin03_cc_03_2_ir_cel_2', 
               'celulas_ctin03_cc_03_1_ir_cel_2', 'celulas_ctin03_cc_03_2_ir_cel_1', 'meteorolgicas_em_03_02_ghi', 
               'celulas_ctin08_cc_08_1_t_mod', 'celulas_ctin08_cc_08_2_t_mod', 'meteorolgicas_em_08_01_gii_rear', 
               'inversores_ctin08_inv_08_08_p', 'inversores_ctin08_inv_08_08_p_dc', 'inversores_ctin08_inv_08_08_eact_tot', 
               'meteorolgicas_em_03_02_gii_rear', 'celulas_ctin03_cc_03_1_t_mod', 'celulas_ctin03_cc_03_2_t_mod', 
               'inversores_ctin03_inv_03_03_p_dc', 'inversores_ctin03_inv_03_03_p', 'inversores_ctin03_inv_03_03_eact_tot', 
               'celulas_ctin08_cc_08_2_t_amb', 'celulas_ctin08_cc_08_1_t_amb', 'celulas_ctin03_cc_03_2_t_amb', 
               'celulas_ctin03_cc_03_1_t_amb', 'inversores_ctin03_strings_string10_pv_i9', 'ttr_potenciaproducible']]

In [6]:
train, test = train_test_split(train, test_size=0.33, shuffle = True)

In [7]:
train.to_csv('data/train_r.csv', index = False)
test.to_csv('data/test_r.csv', index = False)

In [8]:
test

,meteorolgicas_em_08_01_gii,celulas_ctin08_cc_08_2_ir_cel_2,celulas_ctin08_cc_08_2_ir_cel_1,celulas_ctin08_cc_08_1_ir_cel_2,celulas_ctin08_cc_08_1_ir_cel_1,meteorolgicas_em_08_01_ghi,meteorolgicas_em_03_02_gii,celulas_ctin03_cc_03_1_ir_cel_1,celulas_ctin03_cc_03_2_ir_cel_2,celulas_ctin03_cc_03_1_ir_cel_2,...,celulas_ctin03_cc_03_2_t_mod,inversores_ctin03_inv_03_03_p_dc,inversores_ctin03_inv_03_03_p,inversores_ctin03_inv_03_03_eact_tot,celulas_ctin08_cc_08_2_t_amb,celulas_ctin08_cc_08_1_t_amb,celulas_ctin03_cc_03_2_t_amb,celulas_ctin03_cc_03_1_t_amb,inversores_ctin03_strings_string10_pv_i9,ttr_potenciaproducible
16995,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.980000,0.000000,0.000000,0.000,8.471428,8.833333,11.133333,10.600000,NaN,0.000000
12109,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.940000,0.000000,0.000000,0.000,3.557143,3.500000,7.650000,7.185714,NaN,0.000000
12505,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,0.000000,0.000000,0.000,4.377778,4.200000,6.050000,5.380000,NaN,0.000000
4157,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,10.433333,0.000000,0.000000,0.000,10.583333,10.600000,10.560000,10.316666,0.254000,0.000000
7926,502.791667,493.842105,499.00,505.466667,510.730769,496.040541,528.400000,542.071429,528.090909,540.357143,...,37.077777,2.299044,2.252484,0.566,34.233333,28.053846,30.527272,25.700000,12.911229,26.476049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11648,2.000000,5.000000,0.00,2.000000,0.000000,1.333333,1.500000,2.500000,2.500000,2.500000,...,7.050000,0.000000,0.000000,0.000,6.736364,6.233333,7.820000,7.500000,0.286000,0.035317
16605,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,11.100000,10.987500,NaN,NaN,NaN,0.000000
7431,285.954545,250.812500,250.85,257.300000,259.350000,201.160714,299.507042,298.214286,289.636364,304.428571,...,17.266667,1.236044,1.211418,0.305,12.600000,11.584615,13.588889,11.357143,7.747861,14.795298
861,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,25.500000,0.000000,0.000000,0.000,25.620000,25.775000,26.100000,25.675000,NaN,0.000000
10486,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.342857,0.000000,0.000000,0.000,7.116667,6.450000,8.371428,7.833333,NaN,0.000000

In [9]:
encoder = LabelEncoder()
normalize = SimpleImputer(strategy='mean')

for i in zip(train.columns, train.dtypes):
    if i[1]=='O':
        train[i[0]] = train[i[0]].fillna('Unknown')
        train[i[0]] = normalize.fit_transform(encoder.fit_transform(train[i[0]].to_numpy().reshape(-1,1)).reshape(-1,1))
    else:
        train[i[0]].fillna(train[i[0]].abs().mean(), inplace=True)
        train[i[0]] = normalize.fit_transform(numpy.array(train[i[0]].abs()).reshape(-1,1))
for i in zip(test.columns, test.dtypes):
    if i[1]=='O':
        test[i[0]] = test[i[0]].fillna('Unknown')
        test[i[0]] = normalize.fit_transform(numpy.array(encoder.fit_transform(test[i[0]].to_numpy().reshape(-1,1))).reshape(-1,1))
    else:
        test[i[0]].fillna(test[i[0]].abs().mean(), inplace=True)
        test[i[0]] = normalize.fit_transform(numpy.array(test[i[0]]).reshape(-1,1))

In [10]:
train_c_x, train_c_y = train.drop(columns = ['ttr_potenciaproducible']), train['ttr_potenciaproducible']

train_c_x = train_c_x.reset_index().drop(columns=['index'])
train_c_y = train_c_y.reset_index().drop(columns=['index'])

test_c_x, test_c_y = test.drop(columns = ['ttr_potenciaproducible']), test['ttr_potenciaproducible']

test_c_x = test_c_x.reset_index().drop(columns=['index'])
test_c_y = test_c_y.reset_index().drop(columns=['index'])

In [11]:
train_c_x

,meteorolgicas_em_08_01_gii,celulas_ctin08_cc_08_2_ir_cel_2,celulas_ctin08_cc_08_2_ir_cel_1,celulas_ctin08_cc_08_1_ir_cel_2,celulas_ctin08_cc_08_1_ir_cel_1,meteorolgicas_em_08_01_ghi,meteorolgicas_em_03_02_gii,celulas_ctin03_cc_03_1_ir_cel_1,celulas_ctin03_cc_03_2_ir_cel_2,celulas_ctin03_cc_03_1_ir_cel_2,...,celulas_ctin03_cc_03_1_t_mod,celulas_ctin03_cc_03_2_t_mod,inversores_ctin03_inv_03_03_p_dc,inversores_ctin03_inv_03_03_p,inversores_ctin03_inv_03_03_eact_tot,celulas_ctin08_cc_08_2_t_amb,celulas_ctin08_cc_08_1_t_amb,celulas_ctin03_cc_03_2_t_amb,celulas_ctin03_cc_03_1_t_amb,inversores_ctin03_strings_string10_pv_i9
0,441.707317,440.352941,440.050000,441.928571,436.260870,427.793103,439.730337,448.142857,443.000000,440.642857,...,39.283333,40.271428,2.089256,2.039956,0.514,29.627273,29.200000,32.162500,28.540000,12.320857
1,159.547945,158.714286,160.272727,158.117647,158.793103,142.365079,198.142857,193.866667,198.000000,187.785714,...,30.350000,30.736364,0.893641,0.875239,0.220,25.070000,23.633334,24.833334,24.683333,5.403816
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,13.680000,13.933333,0.000000,0.000000,0.000,13.650000,13.712500,13.966667,13.625000,7.512375
3,334.361702,322.650000,329.904762,346.269231,336.142857,359.024691,435.114943,437.000000,411.083333,416.214286,...,37.011111,36.028571,1.822000,1.785044,0.448,27.845455,26.490909,31.025000,29.466667,11.103878
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,11.233333,11.920000,0.000000,0.000000,0.000,11.710000,11.042857,13.457143,12.625000,7.512375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11701,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,12.616667,12.866667,0.000000,0.000000,0.000,11.611111,11.400000,13.183333,12.788889,7.512375
11702,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,11.287500,11.520000,0.000000,0.000000,0.000,11.833333,11.662500,11.850000,11.428571,7.512375
11703,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6.080000,6.450000,0.000000,0.000000,0.000,4.963636,5.157143,7.625000,7.180000,7.512375
11704,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,8.600000,8.500000,0.000000,0.000000,0.000,8.766667,9.020000,9.400000,9.520000,7.512375
11705,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,17.062500,17.200000,0.000000,0.000000,0.000,16.025000,16.180000,17.275000,16.977778,7.512375

In [12]:
class solo_models:
    def __new__(self, train_c_x, train_c_y, test_c_x, test_c_y):
        print('INITIATING PARAMETER')
        self.X_train, self.X_test, self.y_train, self.y_test = train_c_x, test_c_x, train_c_y, test_c_y
        #print("train_c_x:",self.train_c_x.index,"train_c_y:",self.train_c_y.index,"X_tain:",self.X_train.index)
        self.R_Forest_parm = {'n_estimators' : 25, 
                              'min_samples_split' : 2, 
                              'max_depth' : 10, 
                              'min_samples_leaf' : 2, 
                              'random_state' : 42}
        
        self.Extra_parm = {'n_estimators' : 50, 
                           'min_samples_split' : 2, 
                           'max_depth' : 8, 
                           'min_samples_leaf' : 2, 
                           'random_state' : 42}
        
        self.LGBM_R_parm = {'colsample_bytree': 0.6657998165699125,
                           'drop_rate': 0.8303473371870002,
                           'learning_rate': 0.2762739125344964,
                           'max_bin': 9983,
                           'max_depth': 8623,
                           'max_drop': 5480,
                           'min_child_samples': 101,
                           'min_data_in_leaf': 426,
                           'n_estimators': 1628,
                           'num_leaves': 3640,
                           'objective': 'regression_l1',
                           'reg_alpha': 0.39940189926691194,
                           'reg_lambda': 0.9567353299218986,
                           'skip_drop': 0.6274640597528743,
                           'verbosity': -1}
        
        self.XGB_R_parm = {'colsample_bytree' : 0.871893537724492,
                           'gamma' : 1,
                           'learning_rate' : 0.923192518624813,
                           'max_depth' : 15,
                           'min_child_weight' : 1,
                           'n_estimators' : 17748,
                           'reg_alpha' : 45,
                           'reg_lambda' : 0.8598696247943665,
                           'subsample' : 0.9109367356405415,
                           'random_state' : 42}

        self.catboost_params = {'iterations' : 3000,
                                'learning_rate': 0.009, 
                                'depth': 5, 
                                'l2_leaf_reg': 5.5,
                                'min_child_samples' : 102,
                                'od_wait' : 50,
                                'random_state' : 42,
                                'eval_metric': 'RMSE', 
                                'od_type' : 'Iter',
                                'bootstrap_type': 'Bayesian', 
                                'grow_policy' : 'Depthwise',
                                'logging_level' : 'Silent'}
        
        self.DecisionTree = {'max_depth': 6}
        self.settings = {"time_budget": 2000,
                         "metric": "mae",
                         "estimator_list": ["lgbm"],
                         "task": "regression",
                         "log_file_name": "experiment.log",
                         "seed": 41,
                         "eval_method": "cv"
                    }
        self.X_train.to_csv('data/X_train.csv', index = False)
        self.y_train.to_csv('data/y_train.csv', index = False)
        self.X_test.to_csv('data/X_test.csv', index = False)
        self.y_test.to_csv('data/y_test.csv', index = False)
        
        self.models(self)
        self.manual_training(self)
        return {'manual_ensemble' : self.model_collecter, 'stack_ensemble' : self.stack_training(self)}
        
    def models(self):
        print('LOADING MODEL')
        self.model_collecter = {}
        
        self.LGBM_R = LGBMRegressor(**self.LGBM_R_parm)
        self.XGB_R = XGBRegressor(**self.XGB_R_parm)
        self.catboost = CatBoostRegressor(**self.catboost_params)

        self.model_collecter['random_forest'] = BaggingRegressor(estimator = RandomForestRegressor(**self.R_Forest_parm), 
                                                                 n_estimators = 10, random_state = 0)
        self.model_collecter['extra_trees'] = BaggingRegressor(estimator = ExtraTreesRegressor(**self.Extra_parm), 
                                                                 n_estimators = 10, random_state = 0)
        self.model_collecter['GradientBoostingRegressor'] = BaggingRegressor(estimator = GradientBoostingRegressor(learning_rate=0.1, 
                                                                                                                   min_samples_split=500,
                                                                                                                   min_samples_leaf=50,
                                                                                                                   max_depth=8,
                                                                                                                   max_features='sqrt',
                                                                                                                   subsample=0.8,
                                                                                                                   random_state=10), 
                                                                            n_estimators = 10, random_state = 0)
        
        self.model_collecter['DecisionTreeRegressor'] = BaggingRegressor(estimator = DecisionTreeRegressor(**self.DecisionTree), 
                                                                 n_estimators = 10, random_state = 0)
        self.model_collecter['TweedieRegressor'] = BaggingRegressor(estimator = TweedieRegressor(), 
                                                                 n_estimators = 10, random_state = 0)
        self.model_collecter['LinearRegression'] = BaggingRegressor(estimator = LinearRegression(), 
                                                                 n_estimators = 10, random_state = 0)
        
        self.model_collecter['ElasticNet'] = BaggingRegressor(estimator = ElasticNetCV(), n_estimators = 10, random_state = 0)
        self.model_collecter['LassoCV'] = BaggingRegressor(estimator = LassoCV(), n_estimators = 10, random_state = 0)
        self.model_collecter['RidgeCV'] = BaggingRegressor(estimator = RidgeCV(), n_estimators = 10, random_state = 0)
        self.model_collecter['LassoLars'] = BaggingRegressor(estimator = LassoLars(), n_estimators = 10, random_state = 0)
        self.model_collecter['Lasso'] = BaggingRegressor(estimator = Lasso(), n_estimators = 10, random_state = 0)
        self.model_collecter['BayesianRidge'] = BaggingRegressor(estimator = BayesianRidge(), n_estimators = 10, random_state = 0)
        self.model_collecter['SVR'] = BaggingRegressor(estimator = SVR(), n_estimators = 10, random_state = 0)
        self.model_collecter['PLSRegression'] = BaggingRegressor(estimator = PLSRegression(), n_estimators = 10, random_state = 0)
        self.model_collecter['KMeans'] = BaggingRegressor(estimator = KMeans(), n_estimators = 10, random_state = 0)
        #self.model_collecter['GaussianProcessRegressor'] = GaussianProcessRegressor()
        self.model_collecter['MLPRegressor'] = BaggingRegressor(estimator = MLPRegressor(), n_estimators = 10, random_state = 0)
        
    def manual_training(self):
        print('TRAINING')
        
        for i in self.model_collecter.keys():
            print(f'--{i.upper()}')
            #print(self.X_train)
            self.model_collecter[i].fit(self.X_train, self.y_train)
            joblib.dump(self.model_collecter[i], f'model/{i}.pkl')

        print('--CATBOOST')
        cat_features = list(self.X_train.select_dtypes(include=['object', 'category']).columns)
        train_pool = Pool(self.X_train, self.y_train, cat_features=cat_features)
        val_pool = Pool(self.X_test, self.y_test, cat_features=cat_features)
        
        self.catboost.fit(train_pool, eval_set=(val_pool), verbose=100, early_stopping_rounds=100)
        print('--XGBOOST')
        self.XGB_R.fit(self.X_train, self.y_train, eval_set = [(self.X_test, self.y_test)],eval_metric = "rmse", verbose = False)
        print('--LGBOOST')
        self.LGBM_R.fit(self.X_train, self.y_train,eval_set = [(self.X_test, self.y_test)],eval_metric ='rmse')
        
        self.model_collecter['LGBMRegressor'] = self.LGBM_R
        self.model_collecter['XGBRegressor'] = self.XGB_R
        self.model_collecter['CatBoostRegressor'] = self.catboost

        joblib.dump(self.model_collecter['LGBMRegressor'], f'model/LGBMRegressor.pkl')
        joblib.dump(self.model_collecter['XGBRegressor'], f'model/XGBRegressor.pkl')
        joblib.dump(self.model_collecter['CatBoostRegressor'], f'model/CatBoostRegressor.pkl')
        
    def stack_training(self):    
        print('--STACK')
        #self.model_collecter['LGBMRegressor'] = self.LGBM_R
        #self.model_collecter['XGBRegressor'] = self.XGB_R
        #self.model_collecter['CatBoostRegressor'] = self.catboost
        self.stack_model = ['LGBMRegressor',
                            'LGBMRegressor',
                            'CatBoostRegressor',
                            'random_forest',
                            'extra_trees',
                            'GradientBoostingRegressor',
                            'DecisionTreeRegressor']
        
        estimators = [(i, self.model_collecter[i]) for i in self.model_collecter.keys() if i in self.stack_model]
        self.model = StackingRegressor(estimators, final_estimator = RidgeCV())
        self.model.fit(self.X_train, self.y_train)
        joblib.dump(self.model, f'model/STACK.pkl')
        return self.model

In [13]:
E_model = solo_models(train_c_x, train_c_y, test_c_x, test_c_y)

INITIATING PARAMETER
LOADING MODEL
TRAINING
--RANDOM_FOREST
--EXTRA_TREES
--GRADIENTBOOSTINGREGRESSOR
--DECISIONTREEREGRESSOR
--TWEEDIEREGRESSOR
--LINEARREGRESSION
--ELASTICNET
--LASSOCV
--RIDGECV
--LASSOLARS
--LASSO
--BAYESIANRIDGE
--SVR
--PLSREGRESSION
--KMEANS
--MLPREGRESSOR
--CATBOOST
--XGBOOST
--LGBOOST
--STACK