In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['zelestra']

In [2]:
!pip install requests
!pip install tabulate
!pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o

Requirement already satisfied: requests in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (2.32.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from requests) (2025.4.26)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from requests) (2.4.0)

WARNING: You are using pip version 21.2.3; however, version 25.1.1 is available.
You should consider upgrading via the 'C:\Users\venka\Downloads\Zelestra Pytorch tabular\torch_tabular\Scripts\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: tabulate in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (0.9.0)

WARNING: You are using pip version 21.2.3; however, version 25.1.1 is available.
You should consider upgrading via the 'C:\Users\venka\Downloads\Zelestra Pytorch tabular\torch_tabular\Scripts\python.exe -m pip install --upgrade pip' command.

Looking in links: http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html
Collecting h2o
  Downloading h2o-3.46.0.7-py2.py3-none-any.whl (265.9 MB)
Requirement already satisfied: tabulate in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from h2o) (0.9.0)
Requirement already satisfied: requests in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from h2o) (2.32.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from requests->h2o) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from requests->h2o) (2.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from requests->h2o) (3.4.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\venka\downloads\zelestra pytorch tabular\torch_tabular\lib\site-packages (from requests->h2o) (2025.4.26)
Installing collected packages: h2o
Successfully installed h2o-3.46.0.7

WARNING: The repository located at h2o-release.s3.amazonaws.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host h2o-release.s3.amazonaws.com'.
WARNING: You are using pip version 21.2.3; however, version 25.1.1 is available.
You should consider upgrading via the 'C:\Users\venka\Downloads\Zelestra Pytorch tabular\torch_tabular\Scripts\python.exe -m pip install --upgrade pip' command.

In [7]:
import h2o
print(h2o.__version__)
from h2o.automl import H2OAutoML

h2o.init(max_mem_size='16G',port='5092')

3.46.0.7
Checking whether there is an H2O instance running at http://localhost:5092..... not found.
Attempting to start a local H2O server...
; OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-win64) (build 25.192-b01, mixed mode)
  Starting server from C:\Users\venka\Downloads\Zelestra Pytorch tabular\torch_tabular\Lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\venka\AppData\Local\Temp\tmpzyvqdk4i
  JVM stdout: C:\Users\venka\AppData\Local\Temp\tmpzyvqdk4i\h2o_venka_started_from_python.out
  JVM stderr: C:\Users\venka\AppData\Local\Temp\tmpzyvqdk4i\h2o_venka_started_from_python.err
  Server is running at http://127.0.0.1:5092
Connecting to H2O server at http://127.0.0.1:5092 ... successful.

--------------------------  -----------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Asia/Kolkata
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    2 months and 12 days
H2O_cluster_name:           H2O_from_python_venka_m78oda
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    14.22 Gb
H2O_cluster_total_cores:    12
H2O_cluster_allowed_cores:  12
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:5092
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.10.0 final
--------------------------  -----------------------------

In [8]:
%%time
train = h2o.import_file("C:/Users/venka/Downloads/1a513221-3-dataset/dataset/train.csv")
test = h2o.import_file("C:/Users/venka/Downloads/1a513221-3-dataset/dataset/test.csv")

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
CPU times: total: 93.8 ms
Wall time: 1.89 s

In [9]:
train.head()

  id    temperature    irradiance    humidity    panel_age    maintenance_count    soiling_ratio    voltage    current    module_temperature    cloud_coverage    wind_speed    pressure  string_id    error_code    installation_type      efficiency
----  -------------  ------------  ----------  -----------  -------------------  ---------------  ---------  ---------  --------------------  ----------------  ------------  ----------  -----------  ------------  -------------------  ------------
   0        7.81732      576.179     41.2431      32.1355                     4         0.803199  37.4035     1.96379               13.6911            62.494      12.8249       1018.87  A1                                                  0.562096
   1       24.7857       240.004      1.35965     19.9775                     8         0.479456  21.8433     0.241473              27.5451            43.8512     12.012        1025.62  D4           E00           dual-axis                0.396447
   2       46.6527       687.613     91.2654       1.4964                     4         0.822398  48.2229     4.1918                43.3637           nan           1.8144       1010.92  C3           E00                                    0.573776
   3       53.3396       735.141     96.191       18.4916                     3         0.837529  46.2957     0.960567              57.7204            67.3615      8.73626      1021.85  A1                         dual-axis                0.629009
   4        5.57537       12.2412    27.4951      30.7227                     6         0.551833   0          0.898062               6.78626            3.632       0.522684     1008.56  B2           E00           fixed                    0.341874
   5       16.5455       174.455     86.1168      29.8532                     5         0.96288    5.35632    2.87807               19.3923            11.1709      8.5414       1006.96  C3           E00           tracking                 0.376127
   6       18.7281       531.96      91.2523      20.6721                     4         0.911821   0.706348   2.13141               26.5218            31.7364      3.59383      1016.01  A1           E00           fixed                    0.537196
   7       52.0606       420.939     22.0727       4.10632                    3         0.528694  13.2285     3.29924               58.8848            59.1359      8.32173      1030.5   C3           E01           dual-axis                0.46685
   8       24.1801       495.8       48.456       12.0298                     8         0.684327  19.9766     3.25572               30.6393            80.595       1.40046      1012.8   C3                         dual-axis                0.5386
   9       37.896        286.739      8.02347     34.6218                     9         0.83576    1.67091    0.351423              49.2975            34.3584      4.67658      1001.33  C3           E02           tracking                 0.379771
[10 rows x 17 columns]

In [5]:
#object_columns = np.load('../input/standalone-train-and-test-preprocessing/object_columns.npy')

In [6]:
#object_columns

In [7]:
#for f in object_columns:
#    train[f] = train[f].asfactor()
#    test[f] = test[f].asfactor()

In [10]:
x = train.columns[1:-1]
y = 'efficiency'

In [11]:
aml = H2OAutoML(max_models=150, seed=55, max_runtime_secs=40000)
aml.train(x=x, y=y, training_frame=train)

AutoML progress: |
11:38:30.999: AutoML: XGBoost is not available; skipping it.

███████████████████████████████████████████████████████████████ (cancelled) 100%

H2OJobCancelled: Job<$03017f000001e513ffffffff$_83bd0b8b457d317d65b6c86e8a29405e> was cancelled by the user.

In [10]:
# View the AutoML Leaderboard
lb = aml.leaderboard
lb.head(rows=lb.nrows)  # Print all rows instead of default (10 rows)

model_id,mean_residual_deviance,rmse,mse,mae,rmsle
StackedEnsemble_AllModels_AutoML_20250529_023447,0.0105307,0.102619,0.0105307,0.0519612,0.079264
StackedEnsemble_BestOfFamily_AutoML_20250529_023447,0.0105404,0.102667,0.0105404,0.052044,0.079289
DeepLearning_grid_1_AutoML_20250529_023447_model_7,0.0105965,0.102939,0.0105965,0.0513631,0.0795468
DeepLearning_grid_1_AutoML_20250529_023447_model_8,0.0106024,0.102968,0.0106024,0.0505493,0.0796367
DeepLearning_grid_1_AutoML_20250529_023447_model_3,0.0106055,0.102983,0.0106055,0.0525034,0.0794868
DeepLearning_grid_1_AutoML_20250529_023447_model_5,0.0106205,0.103056,0.0106205,0.0510666,0.0796526
GBM_grid_1_AutoML_20250529_023447_model_48,0.0106296,0.1031,0.0106296,0.0528652,0.0795266
XGBoost_grid_1_AutoML_20250529_023447_model_30,0.0106502,0.1032,0.0106502,0.0531379,0.07957
XGBoost_grid_1_AutoML_20250529_023447_model_7,0.0106536,0.103216,0.0106536,0.0529856,0.0795792
GBM_grid_1_AutoML_20250529_023447_model_1,0.0106547,0.103221,0.0106547,0.0529911,0.0795914
DeepLearning_grid_1_AutoML_20250529_023447_model_6,0.0106569,0.103232,0.0106569,0.0518254,0.0797319
XGBoost_3_AutoML_20250529_023447,0.0106624,0.103259,0.0106624,0.0531372,0.0796017
XGBoost_grid_1_AutoML_20250529_023447_model_20,0.0106683,0.103287,0.0106683,0.0530559,0.0796205
DeepLearning_grid_1_AutoML_20250529_023447_model_1,0.0106803,0.103346,0.0106803,0.051442,0.0798498
XGBoost_grid_1_AutoML_20250529_023447_model_27,0.0106925,0.103404,0.0106925,0.0533529,0.0796961
XGBoost_grid_1_AutoML_20250529_023447_model_36,0.0106975,0.103429,0.0106975,0.0533509,0.0797039
DeepLearning_grid_1_AutoML_20250529_023447_model_9,0.01071,0.103489,0.01071,0.0537811,0.0796817
DeepLearning_1_AutoML_20250529_023447,0.0107208,0.103541,0.0107208,0.0527544,0.0798612
GBM_grid_1_AutoML_20250529_023447_model_35,0.0107272,0.103572,0.0107272,0.0537075,0.0797728
GBM_5_AutoML_20250529_023447,0.0107682,0.10377,0.0107682,0.0540941,0.0799032
XGBoost_grid_1_AutoML_20250529_023447_model_3,0.0108077,0.10396,0.0108077,0.0538845,0.0800381
XGBoost_grid_1_AutoML_20250529_023447_model_29,0.0108178,0.104009,0.0108178,0.0537054,0.0800845
DeepLearning_grid_1_AutoML_20250529_023447_model_4,0.0108215,0.104027,0.0108215,0.0525755,0.0802518
GBM_grid_1_AutoML_20250529_023447_model_41,0.0108282,0.104059,0.0108282,0.0543601,0.0800777
GBM_2_AutoML_20250529_023447,0.0108321,0.104078,0.0108321,0.0542756,0.0800781
GBM_grid_1_AutoML_20250529_023447_model_36,0.0108367,0.1041,0.0108367,0.0548675,0.0800528
GBM_grid_1_AutoML_20250529_023447_model_18,0.0108408,0.104119,0.0108408,0.0545215,0.0801061
XGBoost_grid_1_AutoML_20250529_023447_model_2,0.0108447,0.104138,0.0108447,0.0545015,0.0801277
GBM_1_AutoML_20250529_023447,0.0108464,0.104146,0.0108464,0.0541781,0.0801305
XGBoost_grid_1_AutoML_20250529_023447_model_6,0.0108623,0.104222,0.0108623,0.0545193,0.080168
GBM_grid_1_AutoML_20250529_023447_model_6,0.0108653,0.104237,0.0108653,0.0546616,0.0801423
XGBoost_grid_1_AutoML_20250529_023447_model_18,0.0108701,0.10426,0.0108701,0.0543862,0.0801864
XGBoost_grid_1_AutoML_20250529_023447_model_23,0.0108778,0.104297,0.0108778,0.0541577,0.0802744
XGBoost_grid_1_AutoML_20250529_023447_model_33,0.0108822,0.104318,0.0108822,0.0539776,0.0802875
GBM_grid_1_AutoML_20250529_023447_model_9,0.0108837,0.104325,0.0108837,0.0551699,0.0801612
XGBoost_grid_1_AutoML_20250529_023447_model_5,0.0108901,0.104356,0.0108901,0.0540276,0.0803131
GBM_grid_1_AutoML_20250529_023447_model_31,0.0108908,0.104359,0.0108908,0.0549973,0.0802109
XGBoost_grid_1_AutoML_20250529_023447_model_24,0.0108935,0.104372,0.0108935,0.0541946,0.0803148
XGBoost_grid_1_AutoML_20250529_023447_model_17,0.0109039,0.104422,0.0109039,0.0549326,0.0802759
GBM_grid_1_AutoML_20250529_023447_model_11,0.0109093,0.104447,0.0109093,0.0551653,0.0802538
GBM_grid_1_AutoML_20250529_023447_model_17,0.0109171,0.104485,0.0109171,0.0555905,0.0802544
XGBoost_grid_1_AutoML_20250529_023447_model_13,0.0109196,0.104497,0.0109196,0.0554134,0.0802821
XGBoost_1_AutoML_20250529_023447,0.0109202,0.1045,0.0109202,0.0555254,0.0802993
XGBoost_grid_1_AutoML_20250529_023447_model_32,0.0109447,0.104617,0.0109447,0.0551409,0.0803714
GBM_3_AutoML_20250529_023447,0.0109496,0.104641,0.0109496,0.0553252,0.0803966
GLM_grid_1_AutoML_20250529_023447_model_1,0.0109499,0.104642,0.0109499,0.0552242,0.0804348
GBM_grid_1_AutoML_20250529_023447_model_30,0.0109553,0.104667,0.0109553,0.0554232,0.0804134
XGBoost_grid_1_AutoML_20250529_023447_model_11,0.0109575,0.104678,0.0109575,0.0556532,0.0803831
XGBoost_grid_1_AutoML_20250529_023447_model_35,0.0109686,0.104731,0.0109686,0.0550794,0.0804807
XGBoost_grid_1_AutoML_20250529_023447_model_12,0.0109735,0.104755,0.0109735,0.055689,0.0804263
XGBoost_grid_1_AutoML_20250529_023447_model_25,0.0109776,0.104774,0.0109776,0.0555119,0.0804642
DeepLearning_grid_1_AutoML_20250529_023447_model_2,0.0109778,0.104775,0.0109778,0.0533959,0.0806506
GBM_grid_1_AutoML_20250529_023447_model_2,0.0109798,0.104784,0.0109798,0.0557481,0.080412
XGBoost_grid_1_AutoML_20250529_023447_model_1,0.010981,0.10479,0.010981,0.0555736,0.0804978
XGBoost_grid_1_AutoML_20250529_023447_model_26,0.0110141,0.104948,0.0110141,0.0562846,0.0805241
XGBoost_grid_1_AutoML_20250529_023447_model_4,0.0110179,0.104966,0.0110179,0.0558185,0.0806026
XGBoost_grid_1_AutoML_20250529_023447_model_8,0.0110221,0.104986,0.0110221,0.0560267,0.0805819
GBM_grid_1_AutoML_20250529_023447_model_44,0.0110285,0.105017,0.0110285,0.0562054,0.0806068
GBM_grid_1_AutoML_20250529_023447_model_46,0.0110544,0.10514,0.0110544,0.0566256,0.0805969
XRT_1_AutoML_20250529_023447,0.0110781,0.105253,0.0110781,0.0572612,0.0806165
XGBoost_grid_1_AutoML_20250529_023447_model_10,0.0111154,0.10543,0.0111154,0.0566599,0.0808176
DRF_1_AutoML_20250529_023447,0.0111223,0.105462,0.0111223,0.0574588,0.0807543
XGBoost_2_AutoML_20250529_023447,0.0111225,0.105463,0.0111225,0.0571175,0.0808174
GBM_grid_1_AutoML_20250529_023447_model_43,0.0111247,0.105474,0.0111247,0.0568577,0.0808426
GBM_grid_1_AutoML_20250529_023447_model_34,0.0111291,0.105494,0.0111291,0.0569823,0.0807968
GBM_grid_1_AutoML_20250529_023447_model_51,0.0111294,0.105496,0.0111294,0.0569667,0.080794
GBM_4_AutoML_20250529_023447,0.0111414,0.105553,0.0111414,0.0568088,0.0809149
XGBoost_grid_1_AutoML_20250529_023447_model_28,0.0111469,0.105579,0.0111469,0.0570247,0.0808771
XGBoost_grid_1_AutoML_20250529_023447_model_16,0.0111476,0.105582,0.0111476,0.0573139,0.0808669
DeepLearning_grid_1_AutoML_20250529_023447_model_10,0.011169,0.105683,0.011169,0.0536076,0.0813941
GBM_grid_1_AutoML_20250529_023447_model_49,0.0111702,0.105689,0.0111702,0.0572466,0.080895
GBM_grid_1_AutoML_20250529_023447_model_45,0.0111719,0.105697,0.0111719,0.0573864,0.0809198
XGBoost_grid_1_AutoML_20250529_023447_model_9,0.0111763,0.105718,0.0111763,0.0568704,0.081014
GBM_grid_1_AutoML_20250529_023447_model_28,0.0112104,0.105879,0.0112104,0.0574009,0.0811095
GBM_grid_1_AutoML_20250529_023447_model_5,0.0112165,0.105908,0.0112165,0.057418,0.0811056
GBM_grid_1_AutoML_20250529_023447_model_50,0.011222,0.105934,0.011222,0.0576712,0.0810387
XGBoost_grid_1_AutoML_20250529_023447_model_21,0.0112601,0.106113,0.0112601,0.0576243,0.081191
GBM_grid_1_AutoML_20250529_023447_model_19,0.0113142,0.106368,0.0113142,0.0582446,0.081359
XGBoost_grid_1_AutoML_20250529_023447_model_19,0.0113434,0.106505,0.0113434,0.0586465,0.0813584
XGBoost_grid_1_AutoML_20250529_023447_model_31,0.0113716,0.106638,0.0113716,0.0589973,0.0814426
XGBoost_grid_1_AutoML_20250529_023447_model_22,0.0113923,0.106735,0.0113923,0.0586437,0.0815372
XGBoost_grid_1_AutoML_20250529_023447_model_14,0.0114212,0.10687,0.0114212,0.0589718,0.0815705
GBM_grid_1_AutoML_20250529_023447_model_8,0.0115241,0.107351,0.0115241,0.0600277,0.0818717
XGBoost_grid_1_AutoML_20250529_023447_model_15,0.0115354,0.107403,0.0115354,0.0597835,0.0819515
GBM_grid_1_AutoML_20250529_023447_model_40,0.0115499,0.10747,0.0115499,0.0600465,0.0818732
GBM_grid_1_AutoML_20250529_023447_model_22,0.0115965,0.107687,0.0115965,0.0606335,0.081992
XGBoost_grid_1_AutoML_20250529_023447_model_34,0.0117359,0.108333,0.0117359,0.0603405,0.0825576
GBM_grid_1_AutoML_20250529_023447_model_29,0.0118101,0.108674,0.0118101,0.0601531,0.082836
GBM_grid_1_AutoML_20250529_023447_model_39,0.0118367,0.108797,0.0118367,0.0620006,0.0826107
GBM_grid_1_AutoML_20250529_023447_model_24,0.0119597,0.109361,0.0119597,0.0627796,0.0828906
GBM_grid_1_AutoML_20250529_023447_model_26,0.0121431,0.110196,0.0121431,0.0634333,0.0836247
GBM_grid_1_AutoML_20250529_023447_model_16,0.012156,0.110254,0.012156,0.0641767,0.0834132
GBM_grid_1_AutoML_20250529_023447_model_10,0.0127828,0.113061,0.0127828,0.0675089,0.084945
GBM_grid_1_AutoML_20250529_023447_model_42,0.0128052,0.11316,0.0128052,0.0678478,0.0850153
GBM_grid_1_AutoML_20250529_023447_model_12,0.0138456,0.117667,0.0138456,0.0740279,0.0876189
GBM_grid_1_AutoML_20250529_023447_model_47,0.0138471,0.117674,0.0138471,0.0730191,0.0880082
GBM_grid_1_AutoML_20250529_023447_model_13,0.0149157,0.12213,0.0149157,0.0772973,0.0907913
GBM_grid_1_AutoML_20250529_023447_model_7,0.0175351,0.13242,0.0175351,0.0882085,0.0972689
GBM_grid_1_AutoML_20250529_023447_model_15,0.0183848,0.135591,0.0183848,0.0920735,0.099182
GBM_grid_1_AutoML_20250529_023447_model_4,0.0194548,0.139481,0.0194548,0.0977268,0.100405
GBM_grid_1_AutoML_20250529_023447_model_3,0.0194633,0.139511,0.0194633,0.0977286,0.100427
GBM_grid_1_AutoML_20250529_023447_model_25,0.0194932,0.139618,0.0194932,0.0978388,0.100491
GBM_grid_1_AutoML_20250529_023447_model_37,0.0195049,0.13966,0.0195049,0.097865,0.100516
GBM_grid_1_AutoML_20250529_023447_model_33,0.0195056,0.139663,0.0195056,0.0978931,0.100518
GBM_grid_1_AutoML_20250529_023447_model_38,0.0195301,0.13975,0.0195301,0.0979757,0.10057
GBM_grid_1_AutoML_20250529_023447_model_20,0.0195865,0.139952,0.0195865,0.0973605,0.101504
GBM_grid_1_AutoML_20250529_023447_model_23,0.020511,0.143217,0.020511,0.0992458,0.103899
GBM_grid_1_AutoML_20250529_023447_model_14,0.0218835,0.147931,0.0218835,0.0995731,0.107931
GBM_grid_1_AutoML_20250529_023447_model_32,0.0244374,0.156325,0.0244374,0.109059,0.112583
GBM_grid_1_AutoML_20250529_023447_model_21,0.0316295,0.177847,0.0316295,0.112876,0.132341
GBM_grid_1_AutoML_20250529_023447_model_27,0.0928718,0.304749,0.0928718,0.230949,nan

In [11]:
# m = h2o.get_model("StackedEnsemble_AllModels_AutoML_20250528_132029")

In [12]:
# m.full_parameters

In [13]:
# dir(m)

In [14]:
# # The leader model is stored here
# aml.leader

In [15]:
#h2o.remove(train)

In [16]:
preds = aml.predict(test)

stackedensemble prediction progress: |████████████████████████████████████| 100%

In [17]:
sample_submission = pd.read_csv('/kaggle/input/zelestra/sample_submission.csv')
sample_submission.shape

(5, 2)

In [18]:
id = pd.read_csv('/kaggle/input/zelestra/test.csv')['id']
submission = pd.DataFrame({
    'id': id.values,
    'efficiency': preds.as_data_frame()['predict'].values,
})
submission

          id  efficiency
0          0    0.384061
1          1    0.541288
2          2    0.517146
3          3    0.456133
4          4    0.481666
...      ...         ...
11995  11995    0.558263
11996  11996    0.482187
11997  11997    0.623241
11998  11998    0.442842
11999  11999    0.545125

[12000 rows x 2 columns]

In [19]:
submission.to_csv('h2o_automl_submission_15.csv', index=False)