In [1]:
%pip install autogluon scikit-learn==1.5.2

Collecting autogluon
  Downloading autogluon-1.3.1-py3-none-any.whl.metadata (11 kB)
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /opt/conda/lib/python3.10/site-packages (from scikit-learn==1.5.2) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn==1.5.2) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn==1.5.2) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn==1.5.2) (3.5.0)
Collecting autogluon.core==1.3.1 (from autogluon.core[all]==1.3.1->autogluon)
  Downloading autogluon.core-1.3.1-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.features==1.3.1 (from autogluon)
  Downloading autogluon.features-1.3.1-py3-none-any.whl.metadata (11 kB)
Collecting autogluon.tabular==1.3.1 (from autogluon.tabular[all]==1.3.1->autogluon)
  Downloading autogluon.tabular-1.3.1-py3-none-any.whl.metadata (14 kB)
Collecting autogluon.multimodal==1.3.1 (from autogluon)
  Downloading autogluon.multimodal-1.3.1-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries==1.3.1 (from autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading autogluon.timeseries-1.3.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx<4,>=3.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (3.3)
Requirement already satisfied: pandas<2.3.0,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2.2.2)
Requirement already satisfied: tqdm<5,>=4.38 in /opt/conda/lib/python3.10/site-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (4.66.4)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2.32.3)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (3.7.5)
Requirement already satisfied: boto3<2,>=1.10 in /opt/conda/lib/python3.10/site-packages (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.26.100)
Collecting autogluon.common==1.3.1 (from autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon)
  Downloading autogluon.common-1.3.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: ray<2.45,>=2.10.0 in /opt/conda/lib/python3.10/site-packages (from ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (2.24.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==1.3.1->autogluon) (0.2.7)
Requirement already satisfied: pyarrow>=15.0.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.core[all]==1.3.1->autogluon) (17.0.0)
Collecting Pillow<12,>=10.0.1 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading pillow-11.2.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Requirement already satisfied: torch<2.7,>=2.2 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (2.4.0+cpu)
Collecting lightning<2.7,>=2.2 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading lightning-2.5.1.post0-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: transformers<4.50,>=4.38.0 in /opt/conda/lib/python3.10/site-packages (from transformers[sentencepiece]<4.50,>=4.38.0->autogluon.multimodal==1.3.1->autogluon) (4.44.0)
Collecting accelerate<2.0,>=0.34.0 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading accelerate-1.7.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: jsonschema<4.24,>=4.18 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (4.22.0)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - \ | done
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: torchvision<0.22.0,>=0.16.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (0.19.0+cpu)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (0.23.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (1.3)
Requirement already satisfied: torchmetrics<1.8,>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (1.4.1)
Collecting omegaconf<2.4.0,>=2.1.1 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Collecting nltk<3.9,>=3.4.5 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (3.1.4)
Requirement already satisfied: tensorboard<3,>=2.9 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (2.16.2)
Requirement already satisfied: pytesseract<0.4,>=0.3.9 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (0.3.13)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.3.1->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... - done
Requirement already satisfied: pdf2image<1.19,>=1.17.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.multimodal==1.3.1->autogluon) (1.17.0)
Requirement already satisfied: catboost<1.3,>=1.2 in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==1.3.1->autogluon) (1.2.5)
Collecting einops<0.9,>=0.7 (from autogluon.tabular[all]==1.3.1->autogluon)
  Downloading einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: xgboost<3.1,>=2.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==1.3.1->autogluon) (2.0.3)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==1.3.1->autogluon) (2.7.16)
Requirement already satisfied: huggingface-hub[torch] in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==1.3.1->autogluon) (0.24.6)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==1.3.1->autogluon) (4.2.0)
Requirement already satisfied: spacy<3.9 in /opt/conda/lib/python3.10/site-packages (from autogluon.tabular[all]==1.3.1->autogluon) (3.7.5)
Requirement already satisfied: pytorch-lightning in /opt/conda/lib/python3.10/site-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (2.4.0)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading gluonts-0.16.1-py3-none-any.whl.metadata (9.8 kB)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading statsforecast-2.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (29 kB)
Collecting mlforecast<0.14,>0.13 (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading mlforecast-0.13.6-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.11,>=0.2.3 (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading utilsforecast-0.2.10-py3-none-any.whl.metadata (7.4 kB)
Collecting coreforecast<0.0.16,>=0.0.12 (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading coreforecast-0.0.15-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting fugue>=0.9.0 (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading fugue-0.9.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: orjson~=3.9 in /opt/conda/lib/python3.10/site-packages (from autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (3.10.4)
Requirement already satisfied: psutil<7.1.0,>=5.7.3 in /opt/conda/lib/python3.10/site-packages (from autogluon.common==1.3.1->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (5.9.3)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.3.1->autogluon) (21.3)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.10/site-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.3.1->autogluon) (6.0.2)
Requirement already satisfied: safetensors>=0.4.3 in /opt/conda/lib/python3.10/site-packages (from accelerate<2.0,>=0.34.0->autogluon.multimodal==1.3.1->autogluon) (0.4.4)
Collecting botocore<1.30.0,>=1.29.100 (from boto3<2,>=1.10->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon)
  Downloading botocore-1.29.165-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from boto3<2,>=1.10->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from boto3<2,>=1.10->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (0.6.2)
Requirement already satisfied: graphviz in /opt/conda/lib/python3.10/site-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.3.1->autogluon) (0.20.3)
Requirement already satisfied: plotly in /opt/conda/lib/python3.10/site-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.3.1->autogluon) (5.22.0)
Requirement already satisfied: six in /opt/conda/lib/python3.10/site-packages (from catboost<1.3,>=1.2->autogluon.tabular[all]==1.3.1->autogluon) (1.16.0)
Requirement already satisfied: datasets>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (2.21.0)
Requirement already satisfied: dill in /opt/conda/lib/python3.10/site-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (0.3.8)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.10/site-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (3.4.1)
Requirement already satisfied: multiprocess in /opt/conda/lib/python3.10/site-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /opt/conda/lib/python3.10/site-packages (from fsspec[http]>=2021.05.0->evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.3.1->autogluon) (2024.6.1)
Requirement already satisfied: pip in /opt/conda/lib/python3.10/site-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.3.1->autogluon) (24.0)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /opt/conda/lib/python3.10/site-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.3.1->autogluon) (0.0.7)
Requirement already satisfied: fastcore<1.6,>=1.5.29 in /opt/conda/lib/python3.10/site-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.3.1->autogluon) (1.5.55)
Requirement already satisfied: fastprogress>=0.2.4 in /opt/conda/lib/python3.10/site-packages (from fastai<2.9,>=2.3.1->autogluon.tabular[all]==1.3.1->autogluon) (1.0.3)
Collecting triad>=0.9.7 (from fugue>=0.9.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading triad-0.9.8-py3-none-any.whl.metadata (6.3 kB)
Collecting adagio>=0.2.4 (from fugue>=0.9.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading adagio-0.2.6-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pydantic<3,>=1.7 in /opt/conda/lib/python3.10/site-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (2.8.2)
Requirement already satisfied: toolz~=0.10 in /opt/conda/lib/python3.10/site-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in /opt/conda/lib/python3.10/site-packages (from gluonts<0.17,>=0.15.0->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (4.12.2)
Requirement already satisfied: future in /opt/conda/lib/python3.10/site-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.3.1->autogluon) (1.0.0)
Requirement already satisfied: cloudpickle in /opt/conda/lib/python3.10/site-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.3.1->autogluon) (3.0.0)
Requirement already satisfied: py4j in /opt/conda/lib/python3.10/site-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.3.1->autogluon) (0.10.9.7)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.3.1->autogluon) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in /opt/conda/lib/python3.10/site-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.3.1->autogluon) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.10/site-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.3.1->autogluon) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.10/site-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.3.1->autogluon) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from jsonschema<4.24,>=4.18->autogluon.multimodal==1.3.1->autogluon) (0.18.1)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /opt/conda/lib/python3.10/site-packages (from lightning<2.7,>=2.2->autogluon.multimodal==1.3.1->autogluon) (0.11.6)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (4.53.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2.9.0.post0)
Requirement already satisfied: numba in /opt/conda/lib/python3.10/site-packages (from mlforecast<0.14,>0.13->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (0.58.1)
Requirement already satisfied: optuna in /opt/conda/lib/python3.10/site-packages (from mlforecast<0.14,>0.13->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon) (3.6.1)
Collecting window-ops (from mlforecast<0.14,>0.13->autogluon.timeseries==1.3.1->autogluon.timeseries[all]==1.3.1->autogluon)
  Downloading window_ops-0.0.15-py3-none-any.whl.metadata (6.8 kB)
Collecting gdown>=4.0.0 (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==1.3.1->autogluon)
  Downloading gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: click in /opt/conda/lib/python3.10/site-packages (from nltk<3.9,>=3.4.5->autogluon.multimodal==1.3.1->autogluon) (8.1.7)
Requirement already satisfied: regex>=2021.8.3 in /opt/conda/lib/python3.10/site-packages (from nltk<3.9,>=3.4.5->autogluon.multimodal==1.3.1->autogluon) (2024.5.15)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf<2.4.0,>=2.1.1->autogluon.multimodal==1.3.1->autogluon)
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 6.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - done
Requirement already satisfied: colorama in /opt/conda/lib/python3.10/site-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon) (0.4.6)
Collecting model-index (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon)
  Downloading model_index-0.1.11-py3-none-any.whl.metadata (3.9 kB)
Collecting opendatalab (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon)
  Downloading opendatalab-0.0.10-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: rich in /opt/conda/lib/python3.10/site-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon) (13.7.1)
Requirement already satisfied: tabulate in /opt/conda/lib/python3.10/site-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.3.1->autogluon) (0.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas<2.3.0,>=2.0.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.10/site-packages (from pandas<2.3.0,>=2.0.0->autogluon.core==1.3.1->autogluon.core[all]==1.3.1->autogluon) (2024.1)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (3.15.1)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /opt/conda/lib/python3.10/site-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (1.0.8)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /opt/conda/lib/python3.10/site-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (3.20.3)
Requirement already satisfied: aiosignal in /opt/conda/lib/python3.10/site-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (1.3.1)
Requirement already satisfied: frozenlist in /opt/conda/lib/python3.10/site-packages (from ray<2.45,>=2.10.0->ray[default]<2.45,>=2.10.0; extra == "all"->autogluon.core[all]==1.3.1->autogluon) (1.4.1)

In [2]:
import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/zelestra/sample_submission.csv
/kaggle/input/zelestra/train.csv
/kaggle/input/zelestra/test.csv
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/version.txt
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/metadata.json
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/learner.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/predictor.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/utils/data/X.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/utils/data/y.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/trainer.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/dataset_train.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/dataset_val.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T63/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T5/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T24/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T28/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T60/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T36/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T20/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T35/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T50/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T33/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T40/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T58/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T30/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T26/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T10/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T25/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T12/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T13/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T37/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T46/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T1/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T23/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T16/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T64/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T55/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T19/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T3/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T42/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T49/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T54/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T29/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T62/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T52/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T31/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T15/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T8/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T27/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T51/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T11/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T34/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T65/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T6/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T39/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T7/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T44/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T66/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T9/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T22/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T53/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T17/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T38/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T21/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T59/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T4/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T14/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T2/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T57/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T56/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T43/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T48/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T47/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T41/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T18/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T61/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T45/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/LinearModel_BAG_L1/T32/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/dataset_train.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/dataset_val.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F8/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F8/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F2/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F2/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/utils/oof.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F3/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F3/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F6/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F6/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F4/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F4/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F7/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F7/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F1/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F1/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F5/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T5/S1F5/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F8/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F8/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F2/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F2/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/utils/oof.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F3/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F3/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F6/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F6/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F4/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F4/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F7/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F7/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F1/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F1/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F5/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T1/S1F5/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F8/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F8/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F2/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F2/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/utils/oof.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F3/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F3/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F6/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F6/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F4/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F4/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F7/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F7/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F1/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F1/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F5/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T3/S1F5/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F8/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F8/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F2/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F2/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/utils/model_template.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/utils/oof.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F3/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F3/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F6/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F6/xgb.ubj
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F4/model.pkl
/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho/models/XGBoost_BAG_L2/T8/S1F4/xgb.ubj

In [3]:
from autogluon.tabular import TabularDataset, TabularPredictor
from autogluon.common import space

In [4]:
# Load dataset into a TabularDataset
data = TabularDataset('/kaggle/input/zelestra/train.csv')

Loaded data from: /kaggle/input/zelestra/train.csv | Columns = 17 / 17 | Rows = 20000 -> 20000

In [5]:
test = TabularDataset('/kaggle/input/zelestra/test.csv')

Loaded data from: /kaggle/input/zelestra/test.csv | Columns = 16 / 16 | Rows = 12000 -> 12000

In [6]:
# predictor = TabularPredictor(
#     label='efficiency',
#     problem_type='regression',
#     eval_metric='root_mean_squared_error',
# ).fit(
#     train_data=data,
#     time_limit=7200,
#     presets='best_quality',
#     hyperparameters={
#         'XGB': {
#             'n_estimators': space.Int(100, 1000),
#             'max_depth': space.Int(3, 15),
#             'learning_rate': space.Real(1e-4, 0.1, log=True),
#             'subsample': space.Real(0.5, 1.0),
#             'colsample_bytree': space.Real(0.5, 1.0),
#             'gamma': space.Real(0, 5),
#             'min_child_weight': space.Int(1, 10),
#             'reg_alpha': space.Real(0.0, 5.0),
#             'reg_lambda': space.Real(0.0, 5.0),
#             'scale_pos_weight': space.Real(1.0, 10.0),
#         },
#         'CAT': {},  # Use default hyperparams or add tuning params
#         'GBM': {},  # LightGBM (AutoGluon's default key is 'GBM')
#         'LR': {},  # ElasticNet & Lasso (L1 = Lasso, L2 = Ridge)
#     },
#     hyperparameter_tune_kwargs={
#         'num_trials': 200,
#         'scheduler': 'local',
#         'searcher': 'random',
#     }
# )

In [7]:
predictor = TabularPredictor.load("/kaggle/input/autogluon-zelestra/AutogluonModels/ag-20250605_142348/ds_sub_fit/sub_fit_ho")

In [8]:
predictions = predictor.predict(test)

In [9]:
test

,id,temperature,irradiance,humidity,panel_age,maintenance_count,soiling_ratio,voltage,current,module_temperature,cloud_coverage,wind_speed,pressure,string_id,error_code,installation_type
0,0,17.618379,85.449838,90.81542277591531,13.910963,6.0,0.889765,6.370396,0.069101,19.517274,33.509889,7.1819582155525445,1034.782455188643,C3,E01,tracking
1,1,34.826323,722.801748,20.98299301574633,20.916528,4.0,0.590372,30.095867,1.713852,37.421443,32.327060,4.184581989921003,992.3197520437311,D4,E00,NaN
2,2,33.776934,485.491998,55.61404977577451,1.446962,3.0,0.611425,28.424430,1.696936,32.147763,69.613333,6.25944104775485,999.2134568588949,D4,E01,dual-axis
3,3,18.584189,350.022720,49.04476645510075,18.810133,5.0,NaN,7.848038,0.787188,25.734118,42.862760,2.7696074663593944,1026.6500782154521,C3,E02,dual-axis
4,4,43.044908,437.295622,8.761571340027164,NaN,8.0,0.564938,12.300717,1.867620,NaN,51.025763,11.846974043208318,1010.809942771749,B2,NaN,fixed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,11995,40.581656,492.446562,35.49601213333054,4.508170,8.0,NaN,40.883724,3.434505,48.476050,14.015174,3.135128144827662,1008.9662669972856,D4,E00,tracking
11996,11996,16.958524,198.844667,4.063816084298089,4.021203,4.0,0.810999,0.000000,1.290352,23.502657,22.788465,9.36342399338491,1023.566458245707,C3,E02,tracking
11997,11997,24.055333,757.621634,2.7976698608970785,15.253932,3.0,NaN,5.855590,4.835729,31.908375,98.197373,14.3559453768628,1011.6658283571514,A1,E00,NaN
11998,11998,15.623725,177.376256,0.6710490966069793,16.437613,2.0,0.861087,0.000000,1.159060,23.835495,9.581184,6.95866488523872,1017.6572634664706,B2,NaN,dual-axis
11999,11999,13.784361,687.633403,88.44870842331616,2.150407,3.0,0.510835,38.372491,0.968285,19.900598,73.898650,6.169192526827322,1029.156004191692,A1,NaN,dual-axis

In [10]:
predictions

0        0.416598
1        0.539148
2        0.523944
3        0.461052
4        0.467442
           ...
11995    0.533546
11996    0.454306
11997    0.584154
11998    0.429929
11999    0.561128
Name: efficiency, Length: 12000, dtype: float32

In [11]:
sample = pd.read_csv('/kaggle/input/zelestra/sample_submission.csv')

In [12]:
sample.head()

   id  efficiency
0   0    0.415846
1   1    0.578047
2   2    0.478029
3   3    0.391611
4   4    0.469754

In [13]:
id = test.pop('id')

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'id': id,
    'efficiency': predictions
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('submission.csv', index=False)
print("Submission file created: submission.csv")

Submission file created: submission.csv

In [14]:
submission = pd.read_csv('/kaggle/working/submission.csv')
submission.head()

   id  efficiency
0   0    0.416598
1   1    0.539148
2   2    0.523944
3   3    0.461052
4   4    0.467442